/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.9.2                                               */
/*  Date (dd.mm.yyyy): 16.12.2021   Time (hh:mm): 23:58                        */
/*******************************************************************************/


#ifndef _FINALPROJECT_DISPLAY_1_RESOURCES_H_
#define _FINALPROJECT_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_LIME 29
#define DISPLAY_1_COLOR_TABLE_SIZE 30

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_ALIEN2 5
#define GX_PIXELMAP_ID_ALIEN3 6
#define GX_PIXELMAP_ID_ALIEN_1 7
#define GX_PIXELMAP_ID_CHEFAO 8
#define GX_PIXELMAP_ID_CORACAO 9
#define GX_PIXELMAP_ID_IMAGE_FINAL 10
#define GX_PIXELMAP_ID_IMAGE_INICIAL 11
#define GX_PIXELMAP_ID_NAVE 12
#define GX_PIXELMAP_ID_PROJETIL 13
#define GX_PIXELMAP_ID_PROJETIL_ALIEN 14
#define GX_PIXELMAP_ID_RESTART_BUTTON 15
#define GX_PIXELMAP_ID_START_BUTTON 16
#define DISPLAY_1_PIXELMAP_TABLE_SIZE 17

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define DISPLAY_1_STRING_TABLE_SIZE 11

#endif                                       /* sentry                         */
